### PR TITLE
update logo wall

### PR DESCRIPTION
**Pull request by RonaldChicaVera**

### CODE REVIEW

**Review by naeluh — COMMENTED** [review]
@RonaldChicaVera thanks !
Should all these logo size be the same ?

**Comment by RonaldChicaVera** [comment]
@naeluh reused the same sizes of the old logos, should i put other sizes? let me know

**Comment by naeluh** [comment]
Coopervision is a bit small
Does that make sense ?
Hope you are doing great !
Also the space below 'A few of our friends' lets just make that 60px for mobile and desktop
I can update the PR as well
logos

**Comment by RonaldChicaVera** [comment]
@naeluh added the observations and new logos tara asked

**Review by naeluh — APPROVED** [review]

**Pull request merged**
